name: "Setup and install"
description: "Common setup steps for Actions"
inputs:
  registry-url:
    description: "Pass registry URL to setup-node action"
    default: "https://registry.npmjs.org"
    required: false

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.9 # Specifically so changeset version will not have ERR_REQUIRE_ASYNC_MODULE error
        cache: "pnpm"
        registry-url: ${{ inputs.registry_url }}
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
