packages:
  - apps/*
  - packages/*
  - tooling/*
minimumReleaseAge: 10080
catalog:
  typescript: 5.7.3
  react-dom: ^19.0.0
  react: ^19.0.0
  "@types/react": ^19.0.12
  "@types/react-dom": ^19.0.4
  eslint: ^9.20.1
  prettier: ^3.5.3
  tailwindcss: 4.1.11
  "@tailwindcss/vite": 4.1.11
catalogs:
  storybook9:
    "@storybook/addon-docs": 9.1.6
    "@storybook/addon-a11y": 9.1.6
    "@storybook/addon-links": 9.1.6
    "@storybook/addon-themes": 9.1.6
    "@storybook/addon-vitest": 9.1.6
    "@storybook/nextjs": 9.1.6
    "@storybook/react-vite": 9.1.4
    eslint-plugin-storybook: 9.1.6
    storybook: 9.1.6
ignoredBuiltDependencies:
  - "@tailwindcss/oxide"
overrides:
  prettier: ^3.5.0
