name: "Chromatic (PR)"

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "apps/storybook/**"
      - "packages/components/src/**"
      - "packages/theme/src/**"

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    outputs:
      storybookUrl: ${{ steps.chromatic.outputs.storybookUrl }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - name: Run Chromatic
        id: chromatic
        uses: chromaui/action@latest
        env:
          CHROMATIC_BRANCH: ${{ github.event.pull_request.head.ref || github.ref_name }}
          CHROMATIC_SHA: ${{ github.event.pull_request.head.sha || github.ref }}
          CHROMATIC_SLUG: ${{ github.repository }}
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: apps/storybook
          onlyChanged: true
          exitOnceUploaded: true
          autoAcceptChanges: main
          # Skip running Chromatic on dependabot and changeset PRs
          skip: "@(dependabot/**|changeset-release/**)"
