name: Publish to npm registry
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/components/package.json"
      - "packages/theme/package.json"
      - "packages/components/src/**"
      - "packages/theme/src/**"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # For changeset to create a release
      pull-requests: write # For changeset to generate changelog and create a PR
      statuses: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Update npm for OIDC publishing
        # pnpm publish uses npm publish under the hood,
        # which requires npm >= 11.5.1 for OIDC support
        run: pnpm install -g npm@11.6.2

      - name: Build packages
        run: pnpm build --filter=@opengovsg/oui

      - name: Setup .npmrc
        run: |
          echo -e "@opengovsg:registry=https://registry.npmjs.org\n//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > $HOME/.npmrc

      - name: Create Release PR or Publish to npm
        id: changesets
        uses: opengovsg/changesets-action@f68bb4b781c954856eabd2643d4087c8faa97f2a
        with:
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish dev snapshot
        if: steps.changesets.outputs.published != 'true'
        run: |
          git checkout main
          pnpm changeset version --snapshot snapshot
          pnpm changeset publish --tag snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
