name: Publish snapshot to Github registry
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup
        with:
          registry-url: https://npm.pkg.github.com

      - name: Build packages
        run: pnpm build

      - name: Setup .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            @opengovsg:registry=https://npm.pkg.github.com/\n//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
          EOF
      - name: Create Release PR or Publish to Github
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish dev snapshot
        if: steps.changesets.outputs.published != 'true'
        run: |
          git checkout main
          pnpm changeset version --snapshot snapshot
          pnpm changeset publish --tag snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
