name: Publish to Github Packages
on:
  release:
    types: [published]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref}}

      - uses: ./.github/actions/setup
        with:
          registry-url: https://npm.pkg.github.com

      - name: Build packages
        run: pnpm build --filter=@opengovsg/oui

      - name: Setup .npmrc
        run: |
          echo -e "@opengovsg:registry=https://npm.pkg.github.com\n//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > $HOME/.npmrc

      - name: Remove prettier config import in package.json
        # This is a workaround to prevent changeset from failing due to prettier config ESM import
        run: |
          sed -i '/"prettier"\: \"@oui/d' packages/components/package.json

      - name: Publish to GitHub registry
        run: |
          pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
